name: "S3 Archive Upload"
description: "Archive and upload a file path to a designated S3 bucket."
inputs:
  bucket:
    description: "An S3 bucket."
    required: true
  name:
    description: "Name to give the S3 object key."
    required: true
  path:
    description: "One or more file or directory paths to upload."
    required: true
  prefix:
    description: "Prefixed to the uploaded archive name."
    required: false
  gzip:
    description: "Compress the archive using gzip."
    required: false
    default: false
runs:
  using: "node16"
  main: "lib/main.js"
